#!/usr/bin/sh

sxhkd &
numlockx &
~/.config/userscripts/dual-head.sh &
redshift &
lxpolkit &
picom --config ~/.config/picom/picom.cnf -b &
polybar -c ~/.config/polybar/polybar.cnf top &

bspc monitor -d I II III IV V VI VII VIII IX

bspc config border_width                2
bspc config window_gap                  20

bspc config split_ratio                 0.52
bspc config borderless_monocle          false
bspc config gapless_monocle             false

bspc config focused_border_color        #3f51b5
bspc config normal_border_color         #000000

bspc config remove_disabled_monitors    true
bspc config remove_unplugged monitors   true

bspc rule -a Gimp                       desktop='^8' state=floating follow=on
bspc rule -a Firefox                    desktop='^3' follow=on
bspc rule -a Thunderbird                desktop='^4' follow=on
bspc rule -a Virt-manager               desktop='^5' state=floating follow=on
bspc rule -a Pavucontrol                state=floating
bspc rule -a galculator                 state=floating
bspc rule -a lxpolkit                   state=floating
bspc rule -a '*:yad'                    state=floating
