[color]
fg = #e4e4e4
bg = #000000
selection = #424242
comment = #969896

# black
color0 = #000000
color8 = #808080

# red
color1 = #ff5f5f
color9 = #ff8787

# green
color2 = #5fff5f
color10 = #87ff87

# yellow
color3 = #ffa95e
color11 = #ffd787

# blue
color4 = #5fafff
color12 = #87afff

# pink
color5 = #ff5faf
color13 = #ff87af

# cyan
color6 = #5fffff
color14 = #87ffff

# white
color7 = #c0c0c0
color15 = #e4e4e4
