#!/bin/bash

# Custom Rofi Script

BORDER="#5fafff"
SEPARATOR="#000000"
FOREGROUND="#E4E4E4"
BACKGROUND="#000000"
BACKGROUND_ALT="#000000"
HIGHLIGHT_BACKGROUND="#2f4f4f"
HIGHLIGHT_FOREGROUND="#87FFFF"

BLACK="#000000"
WHITE="#5fffff"
RED="#ff5f5f"
GREEN="#5fff5f"
YELLOW="#ffa95e"
BLUE="#5fafff"
PINK="#ff5faf"
CYAN="#5fffff"

# Launch Rofi
rofi -no-lazy-grab -show drun \
-display-drun "Приложения " -drun-display-format "{name}" \
-hide-scrollbar true \
-bw 0 \
-lines 10 \
-line-padding 15 \
-padding 60 \
-width 30 \
-xoffset 10 -yoffset 40 \
-location 1 \
-fullscreen \
-columns 4 \
-show-icons -icon-theme "Numix-Circle-Light" \
-font "Droid Sans Regular 10" \
-color-enabled true \
-color-window "$BACKGROUND,$BORDER,$SEPARATOR" \
-color-normal "$BACKGROUND_ALT,$FOREGROUND,$BACKGROUND_ALT,$HIGHLIGHT_BACKGROUND,$HIGHLIGHT_FOREGROUND" \
-color-active "$BACKGROUND,$BLUE,$BACKGROUND_ALT,$HIGHLIGHT_BACKGROUND,$HIGHLIGHT_FOREGROUND" \
-color-urgent "$BACKGROUND,$YELLOW,$BACKGROUND_ALT,$HIGHLIGHT_BACKGROUND,$HIGHLIGHT_FOREGROUND"
